title: Sentinel
description: Let’s dig into how things really work — from bare metal to high-level code.
show_downloads: false
google_analytics:
theme: jekyll-theme-hacker
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
